{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}
rules:
  # Used to authorize Kubelet requests, ref:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/#kubelet-authorization
  - apiGroups: [""]
    resources:
      # For /metrics/cadvisor.
      - "nodes/metrics"
      # For /stats/summary.
      - "nodes/stats"
      # For /pods (see ref above), and to reach kubelet through the API Server proxy if direct connection fails.
      - "nodes/proxy"
    verbs: ["get", "list"]
  - apiGroups: [ "" ]
    resources:
      # endpoints and services are used for target autodiscovery.
      - "endpoints"
      - "services"
      # nodes is used to fetch node data.
      - "nodes"
    verbs: [ "get", "list", "watch" ]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  {{- if .Values.rbac.pspEnabled }}
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged-{{ template "newrelic.fullname" . }}
    verbs:
      - use
  {{- end -}}
{{- end -}}
